FROM registry.access.redhat.com/ubi10/python-312-minimal:latest

USER 0
COPY pyproject.toml /tmp/src/
COPY soundcheck/__init__.py soundcheck/cli.py soundcheck/check_service.py soundcheck/utils.py /tmp/src/soundcheck/
RUN /usr/bin/fix-permissions /tmp/src
USER 1001

RUN /usr/libexec/s2i/assemble

ENTRYPOINT ["showroom-soundcheck"]
