FROM registry.access.redhat.com/ubi10/python-312-minimal:latest

USER 0
COPY backend/pyproject.toml /tmp/src/
COPY backend/soundcheck/__init__.py backend/soundcheck/cli.py backend/soundcheck/utils.py /tmp/src/soundcheck/
COPY backend/soundcheck/services/__init__.py backend/soundcheck/services/check_service.py /tmp/src/soundcheck/services/
RUN /usr/bin/fix-permissions /tmp/src
USER 1001

RUN /usr/libexec/s2i/assemble

ENTRYPOINT ["showroom-soundcheck"]
