"""auto

Revision ID: c0724c485086
Revises: f1a2b3c4d5e6
Create Date: 2026-04-28 08:35:18.439036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0724c485086'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_check_results_target_id'), ['target_id'], unique=False)

    with op.batch_alter_table('session_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_targets_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_session_id'))

    with op.batch_alter_table('session_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_targets_session_id'))

    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_check_results_target_id'))

    # ### end Alembic commands ###
