---
apiVersion: v1
kind: ConfigMap
metadata:
  name: showroom-soundcheck-config
  namespace: showroom-soundcheck
  labels:
    app.kubernetes.io/name: showroom-soundcheck-app
    app.kubernetes.io/part-of: showroom-soundcheck
data:
  REDIS_URL: "redis://redis:6379"
  CHECK_CONCURRENCY: "20"
  ORCHESTRATION_CONCURRENCY: "10"
  VERIFY_SSL: "false"
  ALLOWED_URL_PATTERNS: "*.redhat.com,*.opentlc.com,*.rhdp.net,*.redhatworkshops.io"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  BABYLON_CLUSTERS: '["/secrets/east.kubeconfig","/secrets/west.kubeconfig"]'
  BABYLON_CATALOG_URLS: '{"east": "https://catalog.demo.redhat.com", "west": "https://babylon-catalog.apps.ocp-us-west-2.infra.open.redhat.com"}'
  ENABLE_DOCS: "true"
