---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: showroom-soundcheck-proxy
  namespace: showroom-soundcheck
  labels:
    app.kubernetes.io/name: showroom-soundcheck-app
    app.kubernetes.io/part-of: showroom-soundcheck
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"showroom-soundcheck"}}
