"""empty message

Revision ID: 1768920cc83e
Revises: 
Create Date: 2026-02-16 09:28:07.841577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1768920cc83e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commit_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('sha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('committed_date', sa.DateTime(), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('insertions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('diff_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('git_repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_commit_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_commit_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_commit_author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_commit_date', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('head_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=False),
    sa.Column('is_force_push', sa.Boolean(), nullable=False),
    sa.Column('previous_head_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_snapshots')
    op.drop_table('git_repos')
    op.drop_table('commit_records')
    # ### end Alembic commands ###
