"""add workshop_guid to targets

Revision ID: 7ba7129e156f
Revises: d2e3f4a5b6c7
Create Date: 2026-05-03 12:35:26.374965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7ba7129e156f'
down_revision: Union[str, Sequence[str], None] = 'd2e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workshop_guid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_targets', schema=None) as batch_op:
        batch_op.drop_column('workshop_guid')

    # ### end Alembic commands ###
